kind: pipeline
type: docker
name: default

trigger:
  event:
    - tag

steps:
  - name: build-and-push
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: tingtingths/rssthis
      tag:
        - latest
        - ${DRONE_TAG}
